const seedItems = [
  // 1) Light Bulbs & Lamps (5)
  {
    name: 'LED Bulb A60 9W Warm White',
    lower_price: 120.0,
    upper_price: 180.0,
    category: 'Light Bulbs & Lamps',
    image_url: 'https://source.unsplash.com/1200x900/?led,bulb,warm',
    description: 'Energy-saving 9W bulb for homes, warm white tone with long life.',
  },
  {
    name: 'LED Bulb A60 12W Daylight',
    lower_price: 150.0,
    upper_price: 220.0,
    category: 'Light Bulbs & Lamps',
    image_url: 'https://source.unsplash.com/1200x900/?led,light,daylight',
    description: 'Bright daylight LED bulb suitable for shops and offices.',
  },
  {
    name: 'LED Floodlight 30W Outdoor',
    lower_price: 1200.0,
    upper_price: 1800.0,
    category: 'Light Bulbs & Lamps',
    image_url: 'https://source.unsplash.com/1200x900/?floodlight,outdoor,lighting',
    description: 'Weather-resistant 30W LED floodlight with strong beam coverage.',
  },
  {
    name: 'Rechargeable Emergency Lamp',
    lower_price: 900.0,
    upper_price: 1400.0,
    category: 'Light Bulbs & Lamps',
    image_url: 'https://source.unsplash.com/1200x900/?emergency,lamp,rechargeable',
    description: 'Portable emergency light with rechargeable battery backup.',
  },
  {
    name: 'LED Tube Light 18W (120cm)',
    lower_price: 350.0,
    upper_price: 520.0,
    category: 'Light Bulbs & Lamps',
    image_url: 'https://source.unsplash.com/1200x900/?tube,light,led',
    description: 'Efficient 18W LED tube for commercial and residential spaces.',
  },

  // 2) Cables & Wiring (5)
  {
    name: 'PVC Copper Cable 1.5mm (100m)',
    lower_price: 5200.0,
    upper_price: 6800.0,
    category: 'Cables & Wiring',
    image_url: 'https://source.unsplash.com/1200x900/?electric,cable,copper',
    description: 'Reliable 1.5mm copper cable coil for lighting circuits.',
  },
  {
    name: 'PVC Copper Cable 2.5mm (100m)',
    lower_price: 7800.0,
    upper_price: 9800.0,
    category: 'Cables & Wiring',
    image_url: 'https://source.unsplash.com/1200x900/?wire,copper,electrical',
    description: 'Heavy-duty 2.5mm cable suitable for socket lines and appliances.',
  },
  {
    name: 'Twin Flexible Wire 2x1.0mm (50m)',
    lower_price: 1900.0,
    upper_price: 2600.0,
    category: 'Cables & Wiring',
    image_url: 'https://source.unsplash.com/1200x900/?flexible,wire,roll',
    description: 'Flexible twin core wire for extension and indoor wiring needs.',
  },
  {
    name: 'PVC Conduit Pipe 20mm (3m)',
    lower_price: 110.0,
    upper_price: 170.0,
    category: 'Cables & Wiring',
    image_url: 'https://source.unsplash.com/1200x900/?conduit,pipe,electrical',
    description: 'Rigid PVC conduit for safe cable routing and protection.',
  },
  {
    name: 'Insulation Tape Pack (10 pcs)',
    lower_price: 180.0,
    upper_price: 280.0,
    category: 'Cables & Wiring',
    image_url: 'https://source.unsplash.com/1200x900/?insulation,tape,electric',
    description: 'Multi-color insulation tapes for secure and clean wiring finishes.',
  },

  // 3) Switches & Sockets (5)
  {
    name: '1-Gang Light Switch',
    lower_price: 130.0,
    upper_price: 220.0,
    category: 'Switches & Sockets',
    image_url: 'https://source.unsplash.com/1200x900/?light,switch,wall',
    description: 'Standard single-gang wall switch with durable mechanism.',
  },
  {
    name: 'Double Socket 13A',
    lower_price: 420.0,
    upper_price: 650.0,
    category: 'Switches & Sockets',
    image_url: 'https://source.unsplash.com/1200x900/?power,socket,electrical',
    description: '13A double outlet socket ideal for home and office usage.',
  },
  {
    name: 'USB Wall Socket 13A + USB',
    lower_price: 850.0,
    upper_price: 1300.0,
    category: 'Switches & Sockets',
    image_url: 'https://source.unsplash.com/1200x900/?usb,socket,wall',
    description: 'Modern wall socket with integrated USB charging ports.',
  },
  {
    name: 'Dimmer Switch 600W',
    lower_price: 780.0,
    upper_price: 1200.0,
    category: 'Switches & Sockets',
    image_url: 'https://source.unsplash.com/1200x900/?dimmer,switch,lighting',
    description: 'Rotary dimmer switch for smooth brightness control.',
  },
  {
    name: 'Weatherproof Outdoor Socket',
    lower_price: 950.0,
    upper_price: 1450.0,
    category: 'Switches & Sockets',
    image_url: 'https://source.unsplash.com/1200x900/?outdoor,socket,waterproof',
    description: 'IP-rated outdoor socket for safe external power access.',
  },

  // 4) Protection & Distribution (5)
  {
    name: 'MCB 10A Single Pole',
    lower_price: 260.0,
    upper_price: 420.0,
    category: 'Protection & Distribution',
    image_url: 'https://source.unsplash.com/1200x900/?circuit,breaker,mcb',
    description: 'Miniature circuit breaker (10A) for branch line protection.',
  },
  {
    name: 'MCB 20A Single Pole',
    lower_price: 280.0,
    upper_price: 460.0,
    category: 'Protection & Distribution',
    image_url: 'https://source.unsplash.com/1200x900/?breaker,panel,electrical',
    description: '20A MCB for heavier domestic and commercial circuits.',
  },
  {
    name: 'RCCB 40A 30mA',
    lower_price: 1800.0,
    upper_price: 2600.0,
    category: 'Protection & Distribution',
    image_url: 'https://source.unsplash.com/1200x900/?rccb,electrical,panel',
    description: 'Residual current breaker for shock and leakage protection.',
  },
  {
    name: 'Distribution Board 8 Way',
    lower_price: 1400.0,
    upper_price: 2300.0,
    category: 'Protection & Distribution',
    image_url: 'https://source.unsplash.com/1200x900/?distribution,board,electric',
    description: '8-way distribution box for organized breaker installations.',
  },
  {
    name: 'Surge Protector 4 Way',
    lower_price: 950.0,
    upper_price: 1600.0,
    category: 'Protection & Distribution',
    image_url: 'https://source.unsplash.com/1200x900/?surge,protector,power',
    description: '4-way surge protected extension for equipment safety.',
  },

  // 5) Tools & Accessories (5)
  {
    name: 'Digital Multimeter',
    lower_price: 1200.0,
    upper_price: 2200.0,
    category: 'Tools & Accessories',
    image_url: 'https://source.unsplash.com/1200x900/?multimeter,electrical,tool',
    description: 'Portable digital multimeter for voltage, current, and continuity tests.',
  },
  {
    name: 'Wire Stripper Tool',
    lower_price: 550.0,
    upper_price: 950.0,
    category: 'Tools & Accessories',
    image_url: 'https://source.unsplash.com/1200x900/?wire,stripper,tool',
    description: 'Precision wire stripper for clean and safe conductor prep.',
  },
  {
    name: 'Insulated Screwdriver Set',
    lower_price: 750.0,
    upper_price: 1300.0,
    category: 'Tools & Accessories',
    image_url: 'https://source.unsplash.com/1200x900/?insulated,screwdriver,set',
    description: 'VDE insulated screwdriver kit for electrical work safety.',
  },
  {
    name: 'Cable Tie Pack (100 pcs)',
    lower_price: 140.0,
    upper_price: 260.0,
    category: 'Tools & Accessories',
    image_url: 'https://source.unsplash.com/1200x900/?cable,tie,pack',
    description: 'Strong nylon cable ties for cable management and bundling.',
  },
  {
    name: 'Junction Box 4x4',
    lower_price: 160.0,
    upper_price: 300.0,
    category: 'Tools & Accessories',
    image_url: 'https://source.unsplash.com/1200x900/?junction,box,electrical',
    description: 'Compact junction box for safe wire connection points.',
  },
];

module.exports = seedItems;
